name: 'Bump Release Version'
description: 'Bump version number to aid automated release processes'
author: 'Florian Wilhelm'
inputs:
  component:
    required: false
    description: "Part of the version number to increment. One of 'major', 'minor', 'patch'."
    default: 'minor'
runs:
  using: 'node16'
  main: 'dist/index.js'
